export const dummyUsers = {
    "student1": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Sophia Wilson" },
    "student2": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Liam Johnson" },
    "student3": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Olivia Brown" },
    "student4": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Noah Davis" },
    "student5": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Emma Garcia" },
    "student6": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "William Martinez" },
    "student7": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Ava Rodriguez" },
    "student8": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "James Hernandez" },
    "student9": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Isabella Lee" },
    "student10": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Benjamin Walker" },
    "student11": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Mia Hall" },
    "student12": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Lucas Allen" },
    "student13": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Amelia Young" },
    "student14": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Henry King" },
    "student15": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Charlotte Wright" },
    "student16": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Alexander Scott" },
    "student17": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Harper Green" },
    "student18": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Daniel Adams" },
    "student19": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Evelyn Baker" },
    "student20": { img: "https://images.pexels.com/photos/2905820/pexels-photo-2905820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", name: "Michael Nelson" }
};
export const dummyData = {
    calenderListItems: {
        "1": [
            {
                title: "science fair setup",
                description: "science club",
                time: "8:00 am",
                bg: "var(--color1)",
            },
            {
                title: "teachers meeting",
                description: "all teacher",
                time: "11:00 am",
                bg: "var(--color2)",
            },
            {
                title: "varsity track meet",
                description: "track team",
                time: "1:00 pm",
                bg: "var(--color3)",
            },
            {
                title: "parents meeting",
                description: "all teachers and parents team",
                time: "4:00 pm",
                bg: "var(--color4)",
            },
        ],
        "2": [
            {
                title: "library inventory",
                description: "admin team",
                time: "9:00 am",
                bg: "var(--color2)",
            },
            {
                title: "art exhibition setup",
                description: "art club",
                time: "3:00 pm",
                bg: "var(--color4)",
            },
        ],
        "4": [
            {
                title: "midterm planning",
                description: "staff only",
                time: "10:00 am",
                bg: "var(--color1)",
            },
        ],
        "6": [
            {
                title: "school cleanup",
                description: "grade 9-11 students",
                time: "8:30 am",
                bg: "var(--color4)",
            },
        ],
        "10": [
            {
                title: "student council meeting",
                description: "council team",
                time: "12:00 pm",
                bg: "var(--color2)",
            },
            {
                title: "soccer match",
                description: "senior boys vs alumni",
                time: "2:30 pm",
                bg: "var(--color3)",
            },
        ],
        "12": [
            {
                title: "lab maintenance",
                description: "lab staff",
                time: "7:45 am",
                bg: "var(--color1)",
            },
        ],
        "15": [
            {
                title: "field trip",
                description: "grade 8 students",
                time: "9:00 am",
                bg: "var(--color4)",
            },
            {
                title: "evening choir rehearsal",
                description: "music club",
                time: "5:30 pm",
                bg: "var(--color3)",
            },
        ],
        "20": [
            {
                title: "exam briefing",
                description: "all students",
                time: "8:00 am",
                bg: "var(--color2)",
            },
        ],
        "22": [
            {
                title: "career day setup",
                description: "staff & external guests",
                time: "1:00 pm",
                bg: "var(--color1)",
            },
        ],
        "25": [
            {
                title: "open day",
                description: "parents and community",
                time: "10:00 am",
                bg: "var(--color4)",
            },
            {
                title: "bake sale",
                description: "home ec club",
                time: "12:00 pm",
                bg: "var(--color4)",
            },
        ],
        "28": [
            {
                title: "final exams begin",
                description: "school-wide",
                time: "8:00 am",
                bg: "var(--color2)",
            },
        ],
        "30": [
            {
                title: "end of month assembly",
                description: "all students and staff",
                time: "2:00 pm",
                bg: "var(--color3)",
            },
        ],
    },
    agenda: [
        { text: "Prep science fair booth", bg: "var(--color1)" },
        { text: "Confirm staff meeting venue", bg: "var(--color2)" },
        { text: "Order snacks for open day", bg: "var(--color4)" },
        { text: "Send reminder for exam schedule", bg: "var(--color2)" },
        { text: "Setup audio for choir performance", bg: "var(--color3)" },
    ],
    studentsList: [
        {
            name: "lucas johnson",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Emily Peterson",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Michael Brown",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Hannah White",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: false },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Oliver Martinez",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Isabelle Garcia",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: false },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Ethan Lee",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Sophia Wilson",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Aiden taylor",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
        {
            name: "Ava Smith",
            attendance: {
                "Fri May 02 2025": { attended: true },
                "Sat May 03 2025": { attended: null },
                "Sun May 04 2025": { attended: null },
                "Mon May 05 2025": { attended: true },
                "Tue May 06 2025": { attended: true },
                "Wed May 07 2025": { attended: true },
                "Thu May 08 2025": { attended: true },
                "Fri May 09 2025": { attended: true },
                "Sat May 10 2025": { attended: null },
                "Sun May 11 2025": { attended: null },
                "Mon May 12 2025": { attended: true },
                "Tue May 13 2025": { attended: true },
                "Wed May 14 2025": { attended: true },
                "Thu May 15 2025": { attended: true },
                "Fri May 16 2025": { attended: true },
                "Sat May 17 2025": { attended: null },
                "Sun May 18 2025": { attended: null }
            },
        },
    ],
    feeCollectionList: [
        { userId: "student1", date: "2015-02-17", class: "11A", tuition: 4500, activitiesFee: 300, miscellaneous: 200, amount: null, status: "paid" },
        { userId: "student2", date: "2015-03-12", class: "10B", tuition: 4200, activitiesFee: 250, miscellaneous: 150, amount: null, status: "overdue" },
        { userId: "student3", date: "2015-04-01", class: "9A", tuition: 4000, activitiesFee: 200, miscellaneous: 100, amount: null, status: "pending" },
        { userId: "student4", date: "2015-02-25", class: "12C", tuition: 4800, activitiesFee: 350, miscellaneous: 250, amount: null, status: "paid" },
        { userId: "student5", date: "2015-05-15", class: "11B", tuition: 4500, activitiesFee: 300, miscellaneous: 200, amount: null, status: "pending" },
        { userId: "student6", date: "2015-03-10", class: "10C", tuition: 4300, activitiesFee: 275, miscellaneous: 180, amount: null, status: "overdue" },
        { userId: "student7", date: "2015-01-20", class: "9B", tuition: 3900, activitiesFee: 180, miscellaneous: 120, amount: null, status: "paid" },
        { userId: "student8", date: "2015-06-11", class: "8A", tuition: 3700, activitiesFee: 160, miscellaneous: 90, amount: null, status: "pending" },
        { userId: "student9", date: "2015-04-18", class: "11A", tuition: 4500, activitiesFee: 300, miscellaneous: 200, amount: null, status: "paid" },
        { userId: "student10", date: "2015-07-21", class: "12A", tuition: 4800, activitiesFee: 350, miscellaneous: 250, amount: null, status: "overdue" },
        { userId: "student11", date: "2015-08-05", class: "10B", tuition: 4200, activitiesFee: 250, miscellaneous: 150, amount: null, status: "pending" },
        { userId: "student12", date: "2015-09-13", class: "9C", tuition: 4000, activitiesFee: 220, miscellaneous: 100, amount: null, status: "paid" },
        { userId: "student13", date: "2015-10-27", class: "11B", tuition: 4500, activitiesFee: 300, miscellaneous: 200, amount: null, status: "paid" },
        { userId: "student14", date: "2015-11-03", class: "8B", tuition: 3600, activitiesFee: 150, miscellaneous: 100, amount: null, status: "overdue" },
        { userId: "student15", date: "2015-12-22", class: "9A", tuition: 4000, activitiesFee: 200, miscellaneous: 100, amount: null, status: "pending" },
        { userId: "student16", date: "2015-02-14", class: "12C", tuition: 4800, activitiesFee: 350, miscellaneous: 250, amount: null, status: "paid" },
        { userId: "student17", date: "2015-03-30", class: "10A", tuition: 4200, activitiesFee: 250, miscellaneous: 150, amount: null, status: "overdue" },
        { userId: "student18", date: "2015-04-09", class: "11C", tuition: 4500, activitiesFee: 300, miscellaneous: 200, amount: null, status: "pending" },
        { userId: "student19", date: "2015-06-20", class: "12A", tuition: 4800, activitiesFee: 350, miscellaneous: 250, amount: null, status: "paid" },
        { userId: "student20", date: "2015-07-11", class: "10C", tuition: 4300, activitiesFee: 275, miscellaneous: 180, amount: null, status: "overdue" }
    ]
};
